databases:
  - name: walkie-postgres
    plan: free
    region: frankfurt
    postgresMajorVersion: "17"
    ipAllowList: []

services:
  - type: web
    name: walkie-web
    runtime: docker
    region: frankfurt
    plan: starter
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    healthCheckPath: /up
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: walkie-postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_LOG_LEVEL
        value: info
      - key: WEB_CONCURRENCY
        value: "2"
      - key: RAILS_MAX_THREADS
        value: "3"
      - key: SOLID_QUEUE_IN_PUMA
        value: "false"
